services:
  plum-api:
    build: .
    container_name: plum-medical-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
    restart: always
